trigger:
  branches:
    include:
      - vcare-master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    net8_0:
      framework: 'net8.0'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8.0.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet test test/unit/SIPSorcery.UnitTests.csproj --framework $(framework) -c Release
  displayName: 'Unit tests'
